language: go

go:
  - 1.4
  - tip

#gcc:
#  - "4.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-4.7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 90

